<?php
/*****************************************************************************************************************
*
* CS50 Final Project
* Harvard Mental Health Forum
*
* Stephanie Havens and Akshay Sharma
*
* register.php
* Usage: registers the user
*
******************************************************************************************************************/




    // configuration
    require("/home/groups/cs50-hmhf/web/includes/config.php");
    
    
    // if form was submitted
    if ($_SERVER["REQUEST_METHOD"] == "POST")
    {
    	//security
        $email = htmlspecialchars($_POST["email"]);
        
        // check that username, password, and confirmation are not left blank
        if(empty($email)) 
            apologize("Please fill out all fields \n");
        $arr = explode('@', $email);
		
		// from http://stackoverflow.com/questions/6232846/best-email-validation-function-in-general-and-specific-college-domain
		if ($arr[1] != 'college.harvard.edu')
		{
   			apologize("Please provide your @college email account. Note, if you are not a
            Harvard undergrad you may not use this site");
		}
       
       //create and encrypt a new password using the first four letters of their email and a random number generated by PHP
        $tmppass = substr($email ,0,4) . rand(0,999);
        $cryptpass = crypt($tmppass);
        $to = $email;
		
		// see if email address already exists
		$exists = query("SELECT email FROM users WHERE email = ?", $to);
		
		// checks that email address is valid
        if(filter_var($to, FILTER_VALIDATE_EMAIL) && empty($exists)){    
            $subject = "Your Harvard Speaks Account";
            // sends them a message with temporary password
            $body = "Hi! \n \n Thanks for registering with Harvard Speaks! Your username is the email address you registered with. \n \n 
The following is your temporary password:\n".$tmppass;
            $headers = "From: cs50-hmhf@hcs.harvard.edu\r\n";
            
            // if it mails, put the information into the database and direct to login
            if (mail($to, $subject, $body, $headers)){
                
                if(query("INSERT INTO users (password, email) VALUES('$cryptpass', '$email')") === false)
           			 apologize("Please choose a new username. \n");
        
        		redirect('login.php');
                }
            else{
                // else didn't deliver
                apologize("Message delivery failed");
                }
            }
            
      	//not allowing for duplicate entries 
        else if($exists== true){
        	apologize("Sorry that email has already been registered. Please search your
        	email for a message from us.");
        }
        
        
    }
    else 
    {
        // else render form
        render("register_form.php", array("title" => "Register"));
    }
?>


